// LuxuryStay sample data
window.LS_DATA = {
  property: {
    name: "LuxuryStay",
    location: "Maison Étoile, Côte d'Azur",
    rooms: 142,
  },
  metrics: {
    occupancy: 87,
    adr: 612, // average daily rate
    revpar: 532,
    arrivalsToday: 24,
    departuresToday: 18,
    inHouse: 96,
  },
  rooms: [
    { num: "201", type: "Deluxe King", floor: 2, status: "occupied", guest: "Mme. Laurent", checkout: "May 06", rate: 480 },
    { num: "202", type: "Deluxe King", floor: 2, status: "available", guest: null, checkout: null, rate: 480 },
    { num: "203", type: "Junior Suite", floor: 2, status: "cleaning", guest: null, checkout: null, rate: 720 },
    { num: "204", type: "Junior Suite", floor: 2, status: "occupied", guest: "Mr. Okafor", checkout: "May 05", rate: 720 },
    { num: "205", type: "Deluxe Twin", floor: 2, status: "maintenance", guest: null, checkout: null, rate: 460 },
    { num: "206", type: "Deluxe King", floor: 2, status: "occupied", guest: "Sato Family", checkout: "May 08", rate: 480 },
    { num: "301", type: "Premier Suite", floor: 3, status: "occupied", guest: "Lord Ashbury", checkout: "May 10", rate: 1240 },
    { num: "302", type: "Deluxe King", floor: 3, status: "available", guest: null, checkout: null, rate: 480 },
    { num: "303", type: "Deluxe King", floor: 3, status: "cleaning", guest: null, checkout: null, rate: 480 },
    { num: "304", type: "Junior Suite", floor: 3, status: "occupied", guest: "Dr. Vasquez", checkout: "May 07", rate: 720 },
    { num: "305", type: "Deluxe Twin", floor: 3, status: "available", guest: null, checkout: null, rate: 460 },
    { num: "306", type: "Premier Suite", floor: 3, status: "occupied", guest: "Mlle. Beaumont", checkout: "May 12", rate: 1240 },
    { num: "401", type: "Penthouse", floor: 4, status: "occupied", guest: "M. Castellanos", checkout: "May 09", rate: 2400 },
    { num: "402", type: "Penthouse", floor: 4, status: "available", guest: null, checkout: null, rate: 2400 },
  ],
  reservations: [
    { id: "RS-2841", guest: "Mme. Cécile Laurent", room: "201", arrival: "May 02", departure: "May 06", nights: 4, status: "in-house", total: 1920, source: "Direct" },
    { id: "RS-2842", guest: "Mr. Adebayo Okafor", room: "204", arrival: "May 03", departure: "May 05", nights: 2, status: "in-house", total: 1440, source: "Concierge" },
    { id: "RS-2843", guest: "Sato Family", room: "206", arrival: "May 04", departure: "May 08", nights: 4, status: "in-house", total: 1920, source: "Direct" },
    { id: "RS-2844", guest: "Lord Ashbury", room: "301", arrival: "May 03", departure: "May 10", nights: 7, status: "in-house", total: 8680, source: "Direct" },
    { id: "RS-2845", guest: "Anika Patel", room: "302", arrival: "May 05", departure: "May 09", nights: 4, status: "confirmed", total: 1920, source: "Travel Agent" },
    { id: "RS-2846", guest: "Theodore Greaves", room: "305", arrival: "May 06", departure: "May 11", nights: 5, status: "confirmed", total: 2300, source: "Direct" },
    { id: "RS-2847", guest: "Dr. Elena Vasquez", room: "304", arrival: "May 02", departure: "May 07", nights: 5, status: "in-house", total: 3600, source: "Direct" },
    { id: "RS-2848", guest: "Henrik Bergström", room: "402", arrival: "May 07", departure: "May 14", nights: 7, status: "confirmed", total: 16800, source: "Direct" },
  ],
  guests: [
    { name: "Lord Ashbury", country: "United Kingdom", visits: 14, lifetime: 52400, tier: "Étoile", room: "301", note: "Prefers Earl Grey, 6:30am" },
    { name: "Mme. Cécile Laurent", country: "France", visits: 8, lifetime: 28100, tier: "Or", room: "201", note: "Allergic to lilies" },
    { name: "Sato Family", country: "Japan", visits: 3, lifetime: 9600, tier: "Argent", room: "206", note: "Two children — connecting rooms" },
    { name: "M. Diego Castellanos", country: "Mexico", visits: 6, lifetime: 41200, tier: "Or", room: "401", note: "Late check-out standing request" },
    { name: "Mlle. Anaïs Beaumont", country: "Belgium", visits: 11, lifetime: 38700, tier: "Or", room: "306", note: "Spa booking auto-confirm" },
    { name: "Dr. Elena Vasquez", country: "Spain", visits: 2, lifetime: 5400, tier: "Argent", room: "304", note: "—" },
  ],
  staff: [
    { name: "Margaux Devereaux", role: "General Manager", dept: "Management", email: "m.devereaux@luxurystay.co", status: "active", since: "2019" },
    { name: "Henri Cassel", role: "Front Office Manager", dept: "Reception", email: "h.cassel@luxurystay.co", status: "active", since: "2021" },
    { name: "Yuki Tanaka", role: "Receptionist", dept: "Reception", email: "y.tanaka@luxurystay.co", status: "active", since: "2023" },
    { name: "Idris Abara", role: "Receptionist", dept: "Reception", email: "i.abara@luxurystay.co", status: "active", since: "2024" },
    { name: "Rosa Mendoza", role: "Head of Housekeeping", dept: "Housekeeping", email: "r.mendoza@luxurystay.co", status: "active", since: "2018" },
    { name: "Adaeze Nwosu", role: "Housekeeping", dept: "Housekeeping", email: "a.nwosu@luxurystay.co", status: "active", since: "2022" },
    { name: "Tomás Reyes", role: "Maintenance Lead", dept: "Maintenance", email: "t.reyes@luxurystay.co", status: "active", since: "2020" },
    { name: "Priya Shankar", role: "Concierge", dept: "Guest Services", email: "p.shankar@luxurystay.co", status: "on-leave", since: "2021" },
  ],
  housekeeping: [
    { room: "203", task: "Departure clean", priority: "high", assigned: "Adaeze N.", eta: "11:30", status: "in-progress" },
    { room: "303", task: "Departure clean", priority: "high", assigned: "Marie L.", eta: "12:00", status: "in-progress" },
    { room: "207", task: "Linen refresh", priority: "med", assigned: "Adaeze N.", eta: "13:15", status: "queued" },
    { room: "401", task: "Turn-down service", priority: "med", assigned: "Sofia R.", eta: "18:30", status: "queued" },
    { room: "501", task: "Deep clean", priority: "low", assigned: "Marie L.", eta: "15:00", status: "queued" },
    { room: "108", task: "Check-out clean", priority: "high", assigned: "Adaeze N.", eta: "10:45", status: "done" },
    { room: "210", task: "Maintenance follow-up", priority: "med", assigned: "Sofia R.", eta: "14:00", status: "done" },
  ],
  maintenance: [
    { id: "MR-118", room: "205", issue: "AC compressor cycling", reported: "May 03 09:14", priority: "high", assigned: "Tomás R.", status: "in-progress" },
    { id: "MR-119", room: "112", issue: "Bathtub drain slow", reported: "May 03 14:22", priority: "med", assigned: "Mateo F.", status: "in-progress" },
    { id: "MR-120", room: "Lobby", issue: "Chandelier bulb (3rd from N)", reported: "May 04 07:50", priority: "low", assigned: "Unassigned", status: "open" },
    { id: "MR-121", room: "308", issue: "TV remote unresponsive", reported: "May 04 08:11", priority: "low", assigned: "Tomás R.", status: "open" },
    { id: "MR-122", room: "Spa", issue: "Sauna thermostat reading high", reported: "May 02 19:30", priority: "high", assigned: "Mateo F.", status: "resolved" },
  ],
  invoices: [
    { id: "INV-04821", guest: "Lord Ashbury", room: "301", amount: 9420, status: "open", issued: "May 03" },
    { id: "INV-04820", guest: "Sato Family", room: "206", amount: 2480, status: "open", issued: "May 04" },
    { id: "INV-04819", guest: "Henrik Bergström", room: "402", amount: 18200, status: "draft", issued: "—" },
    { id: "INV-04818", guest: "Pavlina Novák", room: "108", amount: 1860, status: "paid", issued: "May 03" },
    { id: "INV-04817", guest: "Sébastien Roux", room: "210", amount: 3220, status: "paid", issued: "May 02" },
  ],
  feedback: [
    { guest: "Pavlina Novák", room: "108", rating: 5, comment: "The chamomile turn-down service was a beautiful touch. Henri at the front desk anticipated every request.", date: "May 03" },
    { guest: "Sébastien Roux", room: "210", rating: 4, comment: "Exceptional dining. Room felt slightly warm — perhaps a thermostat calibration.", date: "May 02" },
    { guest: "Anastasia Volkov", room: "402", rating: 5, comment: "Penthouse terrace at sunrise — unforgettable. Will return.", date: "Apr 28" },
  ],
};
